### ISSUE TITLE
error: the legacy LLVM-style asm! syntax is no longer supported

### ISSUE THREAD

**Issue by tuxcanfly** [KZen-networks/thresh-sig-js#16]
https://github.com/rust-lang/rust/issues/70173

**Comment by tuxcanfly** [comment]
I'm seeing this when doing `npm install`. I needed to update `subtle` to the latest version.

**Comment by oleiba** [comment]
Which Rust version are you using?
The library currently supports `rustc 1.38.0-nightly (0b680cfce 2019-07-09)` as detailed in the README and the build script.
Other versions may need special handling. 
If you have a solution please consider a PR.

**Comment by tuxcanfly** [comment]
OK thanks, got it working.

For reference I had to ask `rustup.sh` to install `nightly-2019-07-09`.
