### ISSUE TITLE
Unsupported URL Type "npm:": npm:@types/elliptic@^6.4.8

### ISSUE THREAD

**Issue by coin77** [KZen-networks/thresh-sig-js#3]
Trying to install getting the following error:

npm install @kzen-networks/thresh-sig
npm ERR! code EUNSUPPORTEDPROTOCOL
npm ERR! Unsupported URL Type "npm:": npm:@types/elliptic@^6.4.8

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\nico\AppData\Roaming\npm-cache\_logs\2019-07-17T09_16_08_535Z-debug.log

**Comment by oleiba** [comment]
Hi, which npm version are you on?
Repository was checked against npm >= 6.9.0 (node >= 8.9.0)

**Comment by coin77** [comment]
Hi,

 

node --version

v8.11.2

 

Best Regards,

Nico

**Comment by oleiba** [comment]
npm?

**Comment by coin77** [comment]
npm --version

5.6.0

**Comment by oleiba** [comment]
so please upgrade to npm 6.9.0 and above...
It relates to package aliasing which is support since npm 6.9.0: 
https://stackoverflow.com/questions/17127054/how-do-i-install-a-package-with-npm-with-a-different-custom-module-name

Closing, if you're still running into issues afterwards we can re-open.

**Comment by coin77** [comment]
With the upgrade to 6.10.1 this is solved, although just noticed that Python 2.7 is required.

**Comment by coin77** [comment]
Works with npm 6.10.1.
