### ISSUE TITLE
Convert ECDSA Signature to HEX equivalent

### ISSUE THREAD

**Issue by doheto** [KZen-networks/thresh-sig-js#6]
Hello 👋 

I am using  the ECDSA Sign function. 

I provided a raw TX ( HEX TX) to the ECDSA Sign function 

It returns : 

`EcdsaSignature {
  r:
   '48c84f78d2bfddfcc0ffd00ad2122874b77c14b472ef60ee56b33db4cff24c20',
  s:
   '391ecb9b5763b7686c9291653ba05ab2b84eb49ff53e2159506602ea595b2b5e',
  recid: 0 
}`

My question is simple : is there a way to convert it to an HEX value ? Like a raw signed TX ? 

Thank you

**Comment by oleiba** [comment]
`EcdsaSignature` has a public function `toBuffer()` which returns the Buffer of exactly 64 bytes of the signature.
If you strictly want a string, then you can do `signature.toBuffer().toString('hex')`.
