### ISSUE TITLE
Unable to send signed TX by 

### ISSUE THREAD

**Issue by doheto** [KZen-networks/thresh-sig-js#8]
Hello 

My testnet thresh address is : 

`2MusrKiffVxSqF7DdxKDSMA41JEKoizbCHo`

My Raw Transaction :

`02000000026bade3490fd7baab61dae5e1c63f4ffd76ed3c92067e99204e4ca2109e1064440100000000ffffffff4dd2145b62f017531219dc50a51eb19a3035cd004ebafd8b1fff50a8fdd4ecef0000000000ffffffff0240420f000000000017a91409970857055568059b178fae6baa639d5627031c87a0bb0d000000000017a9141cdd8ea4897b32fe81e7affc36f9d42a1b9b48c38700000000`

My signed TX : 

`723a837df7bbb151fe50a9b73b39327f5dc03b637bacde46c30769670d73b8d54720faac7a41ce1e35a3a1a6641fb9bfc9746e336da49a2ab600d77faac77060`

Sending TX : 

`var dataString = {"jsonrpc":"2.0","id":"1","method":"sendrawtransaction","params":["723a837df7bbb151fe50a9b73b39327f5dc03b637bacde46c30769670d73b8d54720faac7a41ce1e35a3a1a6641fb9bfc9746e336da49a2ab600d77faac77060"]}; 
`

`var options = {
    url: "http://${USER}:${PASS}@127.0.0.1:8332/",
    method: "POST",
    headers: headers,
    body: dataString
  };`

Yet i have this error : 

`{"result":null,"error":{"code":-22,"message":"TX decode failed"},"id":"1"}`

So what's wrong ? is there something missing on my side ? 

May i have an example of how you send a rawtransaction signed using thresh-sig-js ??

**Comment by oleiba** [comment]
It seems that this is an issue with the way you construct and encode a BTC transaction rather than specifically signing it using thresh-sig-js.
I'm closing this issue, but you're invited to send me your code in private so I'll try to help out.
